---

# create a directory and Copy packages in target servers

- name: Create directory /opt/fda/packages in Linux servers
  file:
    path: /usr/java
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: 0755
  tags: prerequisites

- name: Copy Java packages
  copy:
    src: "{{jdk_package}}"
    dest: /usr/java
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: 0755
  tags: prerequisites
    
- name: Unarchive and install Java
  unarchive:
    src:  "/usr/java/{{jdk_package}}"
    dest: /usr/java
    remote_src: yes
  tags: install

- shell: grep {{jdk}}/bin /etc/environment
  changed_when: false
  register: jdk_path_exists
  ignore_errors: yes
  tags: configure

- name: Update environment with the path of jdk installation
  replace:
    path: /etc/environment
    regexp: "^PATH=\""
    replace: "PATH=\"{{jdk}}/bin:"
  when: jdk_path_exists.failed == True
  tags: configure
