---
- name: Update fs.file-max in /etc/sysctl.conf file
  sysctl:
    name: fs.file-max
    value: 1048577
    state: present

- name: Update nofile limits in /etc/security/limits.conf file
  pam_limits:
    domain: '*'
    limit_type: soft
    limit_item: nofile
    value: 500000

- name: Update nofile limits in /etc/security/limits.conf file
  pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: nofile
    value: 500000

- name: Update nofile limits in /etc/security/limits.conf file
  pam_limits:
    domain: root
    limit_type: soft
    limit_item: nofile
    value: 500000

- name: Update nofile limits in /etc/security/limits.conf file
  pam_limits:
    domain: root
    limit_type: hard
    limit_item: nofile
    value: 500000
