---

# Send slack notifications

- name: Send notification message via Slack all options
  slack:
    token: "{{ token }}"
    msg: "{{ message }}"
    channel: "{{ channel }}"
    username: "{{ username }}"
    link_names: 0
    parse: 'none'
  delegate_to: localhost
