kind: Deployment
metadata:
  name: credit-rating
spec:
  selector:
    matchLabels:
      app: credit-rating
      tier: app
  replicas: 1
  template:
    metadata:
      labels:
        app: credit-rating
        tier: app
    spec:
      containers:
      - name: credit-rating
        image: iamveershukla/credit-rating-app:1.0
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 8080
