apiVersion: v1
kind: Service
metadata:
  name: loans-service
  labels:
    app: loans
    tier: app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: loans
    tier: app
