apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-ui
spec:
  selector:
    matchLabels:
      app: loans-ui
      tier: web
  replicas: 1
  template:
    metadata:
      labels:
        app: loans-ui
        tier: webd
    spec:
      containers:
      - name: loans-ui
        image: iamveershukla/loans-ui:1.0
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 4200
