---

# Read file and create message to be send via slack notifications
- name: Download the file
  get_url:
    url: "{{download_link}}"
    dest: /tmp/test.json

- name: Read file in a variable
  set_fact:
    testfile: "{{ lookup('file','/tmp/test.json') | from_json }}"

- name: "INFO: Display the File Contents"
  debug: msg="{{ testfile | json_query('organzations[? (plan_id == `trial` && status == `in_trial` && (`days-remaining-trial` != null && `days-remaining-trial` > `0`) ) || plan_id == `trial` || plan_id == `employee` ].name') | join(', ') }}"

- name: Get organization names and create message
  no_log: True
  set_fact:
    message: "{{ testfile | json_query('organzations[? (plan_id == `trial` && status == `in_trial` && (`days-remaining-trial` != null && `days-remaining-trial` > `0`) ) || plan_id == `trial` || plan_id == `employee` ].name') | join(', ') }}"
