---

# create a directory and Copy packages in target servers

- name: Install Java in RedHat based systems.
  block:
    - include_tasks: install_redhat.yml
  when: ansible_os_family == "RedHat"
  become: yes
  become_method: sudo

- name: Install Java in Debian based systems.
  block:
    - include_tasks: install_debian.yml
  when: ansible_os_family == "Debian"
  become: yes 
  become_method: sudo


