---
# file: appservers.yml
- hosts: appservers
  vars_files: 
    - "~/ansible_roles_prj/environments/{{org_name}}/{{env}}/vault.yml"
    - "~/ansible_roles_prj/environments/{{org_name}}/{{env}}/app_vars"
  tasks:
  - import_role:
      name: prerequisites
    tags: prerequisites
 
  - import_role: 
      name: java
    tags: java

  - import_role:
      name: "{{app_server}}"
